import '@mantine/core/styles.css'
import './globals.css'
import { ColorSchemeScript } from '@mantine/core'
import MainNavigation from '@/components/navigation/MainNavigation'
import type { Metadata } from 'next'
import { Noto_Sans_JP } from 'next/font/google'
import Providers from '../components/Providers'
import { ReactNode } from 'react'

const noto = Noto_Sans_JP({ subsets: ['latin'] })

export const metadata: Metadata = {
    description: 'Generated by create next app',
    title: 'Create Next App'
}

export default function RootLayout({
    children
}: {
  children: ReactNode
}) {
    return (
        <html lang="en">
            <head>
                <ColorSchemeScript />
            </head>
            <body className={noto.className}>
                <Providers>
                    <MainNavigation />
                    <main className="">
                        {children}
                    </main>
                </Providers>
            </body>
        </html>
    )
}
