import './globals.css'
import { HeaderSimple } from '@/components/HeaderSimple'
import type { Metadata } from 'next'
import { Noto_Sans_JP } from 'next/font/google'
import Providers from '../components/Providers'
import { ReactNode } from 'react'

const noto = Noto_Sans_JP({ subsets: ['latin'] })

export const metadata: Metadata = {
    description: 'Generated by create next app',
    title: 'Create Next App'
}

export default function RootLayout({
    children
}: {
  children: ReactNode
}) {
    return (
        <html lang="en">
            <body className={noto.className}>
                <Providers>
                    <HeaderSimple links={[{ label: 'test1', link: '/' }]}/>
                    <main className="flex min-h-screen flex-col items-center justify-between p-24">
                        {children}
                    </main>
                </Providers>
            </body>
        </html>
    )
}
