import '@mantine/core/styles.css'
import './globals.css'
import MainNavigation from '@/components/navigation/MainNavigation'
import type { Metadata } from 'next'
import { Noto_Sans_JP } from 'next/font/google'
import Providers from '../components/Providers'
import { ReactNode } from 'react'

const noto = Noto_Sans_JP({ subsets: ['latin'] })

export const metadata: Metadata = {
    description: 'Generated by create next app',
    title: 'Create Next App'
}

interface LayoutProps {
    children: ReactNode
}

export default function RootLayout({
    children
}: LayoutProps) {
    return (
        <html lang="en">
            <body className={noto.className}>
                <Providers>
                    <MainNavigation>
                        {children}
                    </MainNavigation>
                </Providers>
            </body>
        </html>
    )
}
